# Generated by Django 5.0 on 2023-12-11 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_articles_login1_alter_articles_password1'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.tasks'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='login1',
            field=models.CharField(default='cuRP98Uf', max_length=8, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='password1',
            field=models.CharField(default='aur09b9B', max_length=8, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='image_tasks',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
