# Generated by Django 5.0 on 2023-12-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_articles_login1_alter_articles_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='test',
        ),
        migrations.AddField(
            model_name='articles',
            name='tests',
            field=models.ManyToManyField(blank=True, to='students.tasks', verbose_name='Задания'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='login1',
            field=models.CharField(default='cp4fYF5E', max_length=8, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='password1',
            field=models.CharField(default='PqCPYXrN', max_length=8, verbose_name='Пароль'),
        ),
    ]
