# Generated by Django 5.0 on 2023-12-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_articles_test_articles_tests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='login1',
            field=models.CharField(default='pi3iy3Bp', max_length=8, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='password1',
            field=models.CharField(default='83FR84ZJ', max_length=8, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.articles')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('bal', models.CharField(max_length=200, verbose_name='Набранный бал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.articles', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
