# Generated by Django 5.0 on 2023-12-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_articles_login1_alter_articles_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='count_question',
            field=models.CharField(default=1, max_length=200, verbose_name='Количество вопросов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='login1',
            field=models.CharField(default='j3TE75Yl', max_length=8, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='password1',
            field=models.CharField(default='85JGqyKB', max_length=8, verbose_name='Пароль'),
        ),
    ]
